# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\setUp.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 616)
        Dialog.setModal(True)
        self.labelSetUp = QtWidgets.QLabel(Dialog)
        self.labelSetUp.setGeometry(QtCore.QRect(210, 40, 131, 31))
        self.labelSetUp.setObjectName("labelSetUp")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 120, 451, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.labelNameVote = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelNameVote.setObjectName("labelNameVote")
        self.horizontalLayout.addWidget(self.labelNameVote)
        self.lineEditNameVote = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditNameVote.setObjectName("lineEditNameVote")
        self.horizontalLayout.addWidget(self.lineEditNameVote)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 210, 451, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelDebut = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelDebut.setObjectName("labelDebut")
        self.horizontalLayout_2.addWidget(self.labelDebut)
        self.dateTimeEditDebut = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_2)
        self.dateTimeEditDebut.setDate(QtCore.QDate(2022, 5, 1))
        self.dateTimeEditDebut.setCalendarPopup(True)
        self.dateTimeEditDebut.setObjectName("dateTimeEditDebut")
        self.horizontalLayout_2.addWidget(self.dateTimeEditDebut)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelFin = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelFin.setObjectName("labelFin")
        self.horizontalLayout_2.addWidget(self.labelFin)
        self.dateTimeEditFin = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_2)
        self.dateTimeEditFin.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 7, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEditFin.setCalendarPopup(True)
        self.dateTimeEditFin.setObjectName("dateTimeEditFin")
        self.horizontalLayout_2.addWidget(self.dateTimeEditFin)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 300, 451, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelBDD = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelBDD.setObjectName("labelBDD")
        self.horizontalLayout_3.addWidget(self.labelBDD)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.checkBoxBDDNon = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxBDDNon.setObjectName("checkBoxBDDNon")
        self.horizontalLayout_3.addWidget(self.checkBoxBDDNon)
        spacerItem3 = QtWidgets.QSpacerItem(18, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.checkBoxBDDOui = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxBDDOui.setObjectName("checkBoxBDDOui")
        self.horizontalLayout_3.addWidget(self.checkBoxBDDOui)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 470, 451, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelSystemVote = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelSystemVote.setObjectName("labelSystemVote")
        self.horizontalLayout_4.addWidget(self.labelSystemVote)
        spacerItem4 = QtWidgets.QSpacerItem(28, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.comboBoxSystemVote = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBoxSystemVote.setObjectName("comboBoxSystemVote")
        self.comboBoxSystemVote.addItem("")
        self.comboBoxSystemVote.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxSystemVote)
        self.buttonSetUp = QtWidgets.QPushButton(Dialog)
        self.buttonSetUp.setGeometry(QtCore.QRect(362, 550, 141, 28))
        self.buttonSetUp.setObjectName("buttonSetUp")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(60, 380, 451, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.labelNameBDD = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.labelNameBDD.setObjectName("labelNameBDD")
        self.horizontalLayout_5.addWidget(self.labelNameBDD)
        self.lineEditNameBDD = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEditNameBDD.setObjectName("lineEditNameBDD")
        self.horizontalLayout_5.addWidget(self.lineEditNameBDD)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSetUp.setText(_translate("Dialog", "CREER UNE ELECTION"))
        self.labelNameVote.setText(_translate("Dialog", "NOM DE L\'ELECTION"))
        self.labelDebut.setText(_translate("Dialog", "DEBUT"))
        self.labelFin.setText(_translate("Dialog", "FIN"))
        self.labelBDD.setText(_translate("Dialog", "Disposer vous d\'une base de donnée?"))
        self.checkBoxBDDNon.setText(_translate("Dialog", "NON"))
        self.checkBoxBDDOui.setText(_translate("Dialog", "OUI"))
        self.labelSystemVote.setText(_translate("Dialog", "Mode de scrutin"))
        self.comboBoxSystemVote.setItemText(0, _translate("Dialog", "CONDORCET"))
        self.comboBoxSystemVote.setItemText(1, _translate("Dialog", "JUGEMENT MAJORITAIRE"))
        self.buttonSetUp.setText(_translate("Dialog", "CREER L\'ELECTION"))
        self.labelNameBDD.setText(_translate("Dialog", "NOM BDD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
